/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBondPositionCallbackReceiver,
  IBondPositionCallbackReceiverInterface,
} from "../../../contracts/interfaces/IBondPositionCallbackReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "Epoch",
            name: "expiredWith",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "isSettled",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct BondPosition",
        name: "oldPosition",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "Epoch",
            name: "expiredWith",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "isSettled",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct BondPosition",
        name: "newPosition",
        type: "tuple",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "Epoch",
                name: "epoch",
                type: "uint8",
              },
            ],
            internalType: "struct CouponKey",
            name: "key",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct Coupon[]",
        name: "couponsMinted",
        type: "tuple[]",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "Epoch",
                name: "epoch",
                type: "uint8",
              },
            ],
            internalType: "struct CouponKey",
            name: "key",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct Coupon[]",
        name: "couponsToBurn",
        type: "tuple[]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "bondPositionAdjustCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBondPositionCallbackReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IBondPositionCallbackReceiverInterface {
    return new utils.Interface(_abi) as IBondPositionCallbackReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBondPositionCallbackReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IBondPositionCallbackReceiver;
  }
}
