/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDepositController,
  IDepositControllerInterface,
} from "../../../contracts/interfaces/IDepositController";

const _abi = [
  {
    inputs: [],
    name: "ControllerSlippage",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidAccess",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidMarket",
    type: "error",
  },
  {
    inputs: [],
    name: "NotExpired",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: true,
        internalType: "Epoch",
        name: "epoch",
        type: "uint16",
      },
      {
        indexed: true,
        internalType: "address",
        name: "cloberMarket",
        type: "address",
      },
    ],
    name: "SetCouponMarket",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "positionId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "v",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "r",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "s",
            type: "bytes32",
          },
        ],
        internalType: "struct IController.PermitSignature",
        name: "positionPermitParams",
        type: "tuple",
      },
    ],
    name: "collect",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "lockEpochs",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "minEarnInterest",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "permitAmount",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "deadline",
                type: "uint256",
              },
              {
                internalType: "uint8",
                name: "v",
                type: "uint8",
              },
              {
                internalType: "bytes32",
                name: "r",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "s",
                type: "bytes32",
              },
            ],
            internalType: "struct IController.PermitSignature",
            name: "signature",
            type: "tuple",
          },
        ],
        internalType: "struct IController.ERC20PermitParams",
        name: "tokenPermitParams",
        type: "tuple",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "positionId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "withdrawAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxPayInterest",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "v",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "r",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "s",
            type: "bytes32",
          },
        ],
        internalType: "struct IController.PermitSignature",
        name: "positionPermitParams",
        type: "tuple",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDepositController__factory {
  static readonly abi = _abi;
  static createInterface(): IDepositControllerInterface {
    return new utils.Interface(_abi) as IDepositControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDepositController {
    return new Contract(address, _abi, signerOrProvider) as IDepositController;
  }
}
