sources:
  - name: v2-coupon-finance
    handler:
      graphql:
        endpoint: '{context.url:https://subgraph.satsuma-prod.com/f6a8c4889b7b/clober/v2-coupon-subgraph/api}'
    transforms:
      - autoPagination: {}
  - name: coupon-finance-point
    handler:
      graphql:
        endpoint: '{context.url:https://subgraph.satsuma-prod.com/f6a8c4889b7b/clober/coupon-point-subgraph/api}'
  - name: arbitrum-aave
    handler:
      graphql:
        endpoint: '{context.url:https://api.thegraph.com/subgraphs/name/aave/protocol-v3-arbitrum}'
  - name: clober-v2
    handler:
      graphql:
        endpoint: '{context.url:https://subgraph.satsuma-prod.com/f6a8c4889b7b/clober/v2-core-subgraph/api}'

documents:
  - ./apis/**/*.graphql
  - ./__tests__/**/*.graphql


codegen:
  contextType: 'MeshContext & { url: string }'
