/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  BondPositionLibrary,
  BondPositionLibraryInterface,
} from "../../../../contracts/libraries/BondPosition.sol/BondPositionLibrary";

const _abi = [
  {
    inputs: [],
    name: "InvalidPositionEpoch",
    type: "error",
  },
  {
    inputs: [],
    name: "UnmatchedPosition",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122014c0055f7dcdd9e86ad5f32ef17263f0087fd1160a048cb86a51e777fd62ef0664736f6c63430008130033";

type BondPositionLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BondPositionLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BondPositionLibrary__factory extends ContractFactory {
  constructor(...args: BondPositionLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BondPositionLibrary> {
    return super.deploy(overrides || {}) as Promise<BondPositionLibrary>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): BondPositionLibrary {
    return super.attach(address) as BondPositionLibrary;
  }
  override connect(signer: Signer): BondPositionLibrary__factory {
    return super.connect(signer) as BondPositionLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BondPositionLibraryInterface {
    return new utils.Interface(_abi) as BondPositionLibraryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BondPositionLibrary {
    return new Contract(address, _abi, signerOrProvider) as BondPositionLibrary;
  }
}
