/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILoanPositionManager } from "./ILoanPositionManager";
export type { ILoanPositionManagerTypes } from "./ILoanPositionManagerTypes";
