/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  Signer,
  utils,
} from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IBondPositionManagerTypesInterface extends utils.Interface {
  functions: {};

  events: {
    "RegisterAsset(address)": EventFragment;
    "UpdatePosition(uint256,uint256,uint16)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RegisterAsset"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatePosition"): EventFragment;
}

export interface RegisterAssetEventObject {
  asset: string;
}
export type RegisterAssetEvent = TypedEvent<[string], RegisterAssetEventObject>;

export type RegisterAssetEventFilter = TypedEventFilter<RegisterAssetEvent>;

export interface UpdatePositionEventObject {
  tokenId: BigNumber;
  amount: BigNumber;
  expiredWith: number;
}
export type UpdatePositionEvent = TypedEvent<
  [BigNumber, BigNumber, number],
  UpdatePositionEventObject
>;

export type UpdatePositionEventFilter = TypedEventFilter<UpdatePositionEvent>;

export interface IBondPositionManagerTypes extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBondPositionManagerTypesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "RegisterAsset(address)"(
      asset?: PromiseOrValue<string> | null
    ): RegisterAssetEventFilter;
    RegisterAsset(
      asset?: PromiseOrValue<string> | null
    ): RegisterAssetEventFilter;

    "UpdatePosition(uint256,uint256,uint16)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      expiredWith?: null
    ): UpdatePositionEventFilter;
    UpdatePosition(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      expiredWith?: null
    ): UpdatePositionEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
