/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IController {
  export type PermitSignatureStruct = {
    deadline: PromiseOrValue<BigNumberish>;
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type PermitSignatureStructOutput = [
    BigNumber,
    number,
    string,
    string
  ] & { deadline: BigNumber; v: number; r: string; s: string };

  export type ERC20PermitParamsStruct = {
    permitAmount: PromiseOrValue<BigNumberish>;
    signature: IController.PermitSignatureStruct;
  };

  export type ERC20PermitParamsStructOutput = [
    BigNumber,
    IController.PermitSignatureStructOutput
  ] & {
    permitAmount: BigNumber;
    signature: IController.PermitSignatureStructOutput;
  };
}

export interface ILeverageAdapterInterface extends utils.Interface {
  functions: {
    "giveManagerAllowance(address)": FunctionFragment;
    "leverage(address,address,uint256,uint256,uint256,uint8,bytes,(uint256,(uint256,uint8,bytes32,bytes32)))": FunctionFragment;
    "leverageMore(uint256,uint256,uint256,uint256,bytes,(uint256,uint8,bytes32,bytes32),(uint256,(uint256,uint8,bytes32,bytes32)))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "giveManagerAllowance" | "leverage" | "leverageMore"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "giveManagerAllowance",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "leverage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      IController.ERC20PermitParamsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "leverageMore",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      IController.PermitSignatureStruct,
      IController.ERC20PermitParamsStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "giveManagerAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "leverage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "leverageMore",
    data: BytesLike
  ): Result;

  events: {
    "SetCouponMarket(address,uint8,address)": EventFragment;
    "SetManagerAllowance(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetCouponMarket"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetManagerAllowance"): EventFragment;
}

export interface SetCouponMarketEventObject {
  asset: string;
  epoch: number;
  cloberMarket: string;
}
export type SetCouponMarketEvent = TypedEvent<
  [string, number, string],
  SetCouponMarketEventObject
>;

export type SetCouponMarketEventFilter = TypedEventFilter<SetCouponMarketEvent>;

export interface SetManagerAllowanceEventObject {
  token: string;
}
export type SetManagerAllowanceEvent = TypedEvent<
  [string],
  SetManagerAllowanceEventObject
>;

export type SetManagerAllowanceEventFilter =
  TypedEventFilter<SetManagerAllowanceEvent>;

export interface ILeverageAdapter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ILeverageAdapterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    giveManagerAllowance(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    leverage(
      collateralToken: PromiseOrValue<string>,
      debtToken: PromiseOrValue<string>,
      collateralAmount: PromiseOrValue<BigNumberish>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      maxPayInterest: PromiseOrValue<BigNumberish>,
      loanEpochs: PromiseOrValue<BigNumberish>,
      swapData: PromiseOrValue<BytesLike>,
      collateralPermitParams: IController.ERC20PermitParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    leverageMore(
      positionId: PromiseOrValue<BigNumberish>,
      collateralAmount: PromiseOrValue<BigNumberish>,
      debtAmount: PromiseOrValue<BigNumberish>,
      maxPayInterest: PromiseOrValue<BigNumberish>,
      swapData: PromiseOrValue<BytesLike>,
      positionPermitParams: IController.PermitSignatureStruct,
      collateralPermitParams: IController.ERC20PermitParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  giveManagerAllowance(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  leverage(
    collateralToken: PromiseOrValue<string>,
    debtToken: PromiseOrValue<string>,
    collateralAmount: PromiseOrValue<BigNumberish>,
    borrowAmount: PromiseOrValue<BigNumberish>,
    maxPayInterest: PromiseOrValue<BigNumberish>,
    loanEpochs: PromiseOrValue<BigNumberish>,
    swapData: PromiseOrValue<BytesLike>,
    collateralPermitParams: IController.ERC20PermitParamsStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  leverageMore(
    positionId: PromiseOrValue<BigNumberish>,
    collateralAmount: PromiseOrValue<BigNumberish>,
    debtAmount: PromiseOrValue<BigNumberish>,
    maxPayInterest: PromiseOrValue<BigNumberish>,
    swapData: PromiseOrValue<BytesLike>,
    positionPermitParams: IController.PermitSignatureStruct,
    collateralPermitParams: IController.ERC20PermitParamsStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    giveManagerAllowance(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    leverage(
      collateralToken: PromiseOrValue<string>,
      debtToken: PromiseOrValue<string>,
      collateralAmount: PromiseOrValue<BigNumberish>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      maxPayInterest: PromiseOrValue<BigNumberish>,
      loanEpochs: PromiseOrValue<BigNumberish>,
      swapData: PromiseOrValue<BytesLike>,
      collateralPermitParams: IController.ERC20PermitParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    leverageMore(
      positionId: PromiseOrValue<BigNumberish>,
      collateralAmount: PromiseOrValue<BigNumberish>,
      debtAmount: PromiseOrValue<BigNumberish>,
      maxPayInterest: PromiseOrValue<BigNumberish>,
      swapData: PromiseOrValue<BytesLike>,
      positionPermitParams: IController.PermitSignatureStruct,
      collateralPermitParams: IController.ERC20PermitParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SetCouponMarket(address,uint8,address)"(
      asset?: PromiseOrValue<string> | null,
      epoch?: PromiseOrValue<BigNumberish> | null,
      cloberMarket?: PromiseOrValue<string> | null
    ): SetCouponMarketEventFilter;
    SetCouponMarket(
      asset?: PromiseOrValue<string> | null,
      epoch?: PromiseOrValue<BigNumberish> | null,
      cloberMarket?: PromiseOrValue<string> | null
    ): SetCouponMarketEventFilter;

    "SetManagerAllowance(address)"(
      token?: PromiseOrValue<string> | null
    ): SetManagerAllowanceEventFilter;
    SetManagerAllowance(
      token?: PromiseOrValue<string> | null
    ): SetManagerAllowanceEventFilter;
  };

  estimateGas: {
    giveManagerAllowance(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    leverage(
      collateralToken: PromiseOrValue<string>,
      debtToken: PromiseOrValue<string>,
      collateralAmount: PromiseOrValue<BigNumberish>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      maxPayInterest: PromiseOrValue<BigNumberish>,
      loanEpochs: PromiseOrValue<BigNumberish>,
      swapData: PromiseOrValue<BytesLike>,
      collateralPermitParams: IController.ERC20PermitParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    leverageMore(
      positionId: PromiseOrValue<BigNumberish>,
      collateralAmount: PromiseOrValue<BigNumberish>,
      debtAmount: PromiseOrValue<BigNumberish>,
      maxPayInterest: PromiseOrValue<BigNumberish>,
      swapData: PromiseOrValue<BytesLike>,
      positionPermitParams: IController.PermitSignatureStruct,
      collateralPermitParams: IController.ERC20PermitParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    giveManagerAllowance(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    leverage(
      collateralToken: PromiseOrValue<string>,
      debtToken: PromiseOrValue<string>,
      collateralAmount: PromiseOrValue<BigNumberish>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      maxPayInterest: PromiseOrValue<BigNumberish>,
      loanEpochs: PromiseOrValue<BigNumberish>,
      swapData: PromiseOrValue<BytesLike>,
      collateralPermitParams: IController.ERC20PermitParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    leverageMore(
      positionId: PromiseOrValue<BigNumberish>,
      collateralAmount: PromiseOrValue<BigNumberish>,
      debtAmount: PromiseOrValue<BigNumberish>,
      maxPayInterest: PromiseOrValue<BigNumberish>,
      swapData: PromiseOrValue<BytesLike>,
      positionPermitParams: IController.PermitSignatureStruct,
      collateralPermitParams: IController.ERC20PermitParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
