/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iBondPositionManagerSol from "./IBondPositionManager.sol";
export type { iBondPositionManagerSol };
import type * as iCouponOracleSol from "./ICouponOracle.sol";
export type { iCouponOracleSol };
import type * as iLoanPositionManagerSol from "./ILoanPositionManager.sol";
export type { iLoanPositionManagerSol };
import type * as iPositionManagerSol from "./IPositionManager.sol";
export type { iPositionManagerSol };
export type { IAaveTokenSubstitute } from "./IAaveTokenSubstitute";
export type { IAssetPool } from "./IAssetPool";
export type { IBorrowController } from "./IBorrowController";
export type { IController } from "./IController";
export type { ICouponLiquidator } from "./ICouponLiquidator";
export type { ICouponManager } from "./ICouponManager";
export type { ICouponPositionHook } from "./ICouponPositionHook";
export type { IDepositController } from "./IDepositController";
export type { IERC1155Permit } from "./IERC1155Permit";
export type { IERC721Permit } from "./IERC721Permit";
export type { IFallbackOracle } from "./IFallbackOracle";
export type { ILeverageAdapter } from "./ILeverageAdapter";
export type { IPositionLocker } from "./IPositionLocker";
export type { IRepayAdapter } from "./IRepayAdapter";
export type { ISubstitute } from "./ISubstitute";
