/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICouponOracle } from "./ICouponOracle";
export type { ICouponOracleTypes } from "./ICouponOracleTypes";
